baseURL = "https://epic-lichterman-3494de.netlify.app/"
languageCode = "en-us"
title = "Decolonizing New Mexico"
theme = "dcnmTheme"
relativeURLs = "true"
enableRobotsTXT = "true"
[params]
  author = "Dr. Estevan Gálvez Rael"
  subtitle = "Remembering, Reimagining and Recovering"
  description = "The Decolonization of New Mexico"