baseURL = "https://epic-lichterman-3494de.netlify.app/"
languageCode = "en-us"
title = "Decolonizing New Mexico"
theme = "dcnmTheme"
relativeURLs = "true"
enableRobotsTXT = "true"
sectionPagesMenu = "main"

[params]
  author = "Dr. Estevan Rael–Gálvez"
  design = "ricardogalvez.design"
  development ="Ricardo E. Gálvez"
  subtitle = "Remembering, Reimagining and Recovering"
  description = "The Decolonization of New Mexico"
  heroimage = "https://res.cloudinary.com/toupeeproofbullets/image/upload/v1598883685/dcnm/IMG_0569.jpg"
  placeHolderSVG = "/images/placeHolding.svg"  
  [params.cloudinary]
    base_url = "https://res.cloudinary.com/toupeeproofbullets/image/upload/"
    folder = "/dcnm/"
    class = "cld-responsive"
  [params.style]
    homepage = 'home-page'
    interiorpage = 'interior-page'
    layouttest = 'layout-test'
  [params.meta]
      url = "http://decolonizingnewmexico.com"
      cardImage = "https://res.cloudinary.com/toupeeproofbullets/image/upload/v1612896174/dcnm/dcnm_card.png"
[menu]
  [[ menu.hp ]]
    identifier = "Table of Contents"
    name = "Table of Contents"
    url = "#table-of-contents"
    weight = -1
  [[ menu.hp ]]  
    identifier = "About this Project"
    name = "About this Project"
    url = "#about-this-project"
    weight = 1

#   [[menu.main]]
#     identifier = "Chapters"
#     name = "Chapters"
#     url = "/chapters/"
#     weight = -110