baseURL = "https://epic-lichterman-3494de.netlify.app/"
languageCode = "en-us"
title = "Decolonizing New Mexico"
theme = "dcnmTheme"
relativeURLs = "true"
enableRobotsTXT = "true"
sectionPagesMenu = "main"

[params]
  author = "Dr. Estevan Rael–Gálvez"
  subtitle = "Remembering, Reimagining and Recovering"
  description = "The Decolonization of New Mexico"
  hero-image = "https://res.cloudinary.com/toupeeproofbullets/image/upload/v1598883685/dcnm/IMG_0569.jpg"
  
  [params.style]
    homepage = 'home-page'
    interiorpage = 'interior-page'
    
# [menu]
#   [[menu.main]]
#     identifier = "Chapters"
#     name = "Chapters"
#     url = "/chapters/"
#     weight = -110
